# Alternating Linear approximation of the ISA (aLISA) method

## Non-linear optimization problem

In [1]:
import numpy as np
from setup import prepare_argument_dict, prepare_grid_and_dens, print_results

from horton_part import BasisFuncHelper, ExpBasisFuncHelper, LinearISAWPart


### Convex optimization method


In [2]:
mol, grid, rho = prepare_grid_and_dens("data/h2o.fchk")


def use_cvxopt_solver():
    """Local LISA by solving convex optimization problem."""
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = "cvxopt"
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


use_cvxopt_solver()

The number of electrons: 10.000003764139395
Coordinates of the atoms 
 [[ 0.     0.     0.224]
 [-0.     1.457 -0.896]
 [-0.    -1.457 -0.896]]
Atomic numbers of the atom 
 [8 1 1]

Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-

### Trust-region method

In [3]:
def use_trust_region_implicit_constr():
    """Local LISA by solving convex optimization problem."""
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = "trust-region"
    kwargs["solver_options"] = {"explicit_constr": False}
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


use_trust_region_implicit_constr()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/optimize/_hessian_update_strategy.py:182: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  warn('delta_grad == 0.0. Check if the approximated '


        4   9.43139e-03   6.28939e-02
        5   6.28278e-03   5.43357e-02
        6   4.36176e-03   4.91977e-02
        7   3.13724e-03   4.59788e-02
        8   2.32439e-03   4.39260e-02
        9   1.76663e-03   4.25672e-02
       10   1.37236e-03   4.16535e-02
       11   1.08426e-03   4.10372e-02
       12   8.69002e-04   4.05994e-02
       13   7.07334e-04   4.02827e-02
       14   5.79412e-04   4.00938e-02
       15   4.79068e-04   3.99380e-02
       16   3.98152e-04   3.98321e-02
       17   3.34015e-04   3.97421e-02
       18   2.81002e-04   3.96912e-02
       19   2.37413e-04   3.96482e-02
       20   2.01270e-04   3.96150e-02
       21   1.71392e-04   3.95866e-02
       22   1.46297e-04   3.95722e-02
       23   1.25170e-04   3.95506e-02
       24   1.08530e-04   3.95197e-02
       25   9.42482e-05   3.95398e-02
       26   8.01395e-05   3.95303e-02
       27   6.95924e-05   3.95253e-02
       28   6.02034e-05   3.95269e-02
       29   5.21416e-05   3.95200e-02
       30   

## Non-linear equations (fixed-point equations)

### Self-consistent method


In [4]:
def use_sc_solver():
    """Self-consistent solver."""
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = "sc"
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


use_sc_solver()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   

### Direct Inversion in Iterative Space (DIIS)

This method has been extensively used to solve self-consistent field (SCF) problems in the fields of quantum chemistry and physics. In this tutorial, we employ this method to accelerate the solving of fixed-point problems.

It should be noted that one potential issue with this method is that non-negative parameters cannot be guaranteed during optimization in the conventional DIIS approach. Although this issue can be addressed by explicitly introducing constraints to the linear combination coefficients, key concepts in DIIS, numerical issues may still arise, such as singular matrices or convergence problems.

In [5]:
def use_diis_solver():
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = "diis"
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


use_diis_solver()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   

### Newton Method

The final method is the Newton method. Similarly to the previous methods, the Newton method cannot guarantee non-negative parameters, and negative pro-atom densities may arise during optimization. To address this, one might need to modify the hyper-parameters used in the method for different systems, which can make it less robust.

In [6]:
def newton_method():
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = "newton"
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


newton_method()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   

## Customized Methods

One can also apply customized solvers. Next, we will implement and apply a modified version of the self-consistent method.

In [7]:
def customize_self_consistent_solver(
    bs_funcs,
    rho,
    propars,
    points,
    weights,
    threshold,
    logger,
    density_cutoff,
    negative_cutoff,
    population_cutoff,
):
    r"""
    Optimize parameters for proatom density functions using a self-consistent (SC) method.

    .. math::

        N_{Ai} = \int \rho_A(r) \frac{\rho_{Ai}^0(r)}{\rho_A^0(r)} dr

    Parameters
    ----------
    bs_funcs : 2D np.ndarray
        Basis functions array with shape (M, N), where 'M' is the number of basis functions
        and 'N' is the number of grid points.
    rho : 1D np.ndarray
        Spherically-averaged atomic density as a function of radial distance, with shape (N,).
    propars : 1D np.ndarray
        Pro-atom parameters with shape (M). 'M' is the number of basis functions.
    points : 1D np.ndarray
        Radial coordinates of grid points, with shape (N,).
    weights : 1D np.ndarray
        Weights for integration, including the angular part (4πr²), with shape (N,).
    threshold : float
        Convergence threshold for the iterative process.
    density_cutoff : float
        Density values below this cutoff are considered invalid.
    negative_cutoff : float
        The value less than `negative_cutoff` is treated as negative.
    population_cutoff : float
        The criteria for the difference between the sum of propars and reference population.


    Returns
    -------
    1D np.ndarray
        Optimized proatom parameters.

    Raises
    ------
    RuntimeError
        If the inner iteration does not converge.

    """
    pro_shells = bs_funcs * propars[:, None]
    pro_density = np.einsum("ij->j", pro_shells)
    sick = (rho < density_cutoff) | (pro_density < density_cutoff)
    ratio = np.divide(rho, pro_density, out=np.zeros_like(rho), where=~sick)
    propars[:] = np.einsum("p,ip->i", weights, pro_shells * ratio)
    return propars

In [8]:
def customized_self_consistent_method():
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = customize_self_consistent_solver
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


customized_self_consistent_method()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   

One can also apply customized basis functions using the `ExpBasisFuncHelper` class. First, we need to define the basis functions, which should adhere to the following general format:

$$
  f_{ak} = c_{ak} \exp^{-\alpha_{ak} |r|^{n_{ak}}}
$$

Here, $c_{ak}$ represents the prefactors and the pro-atom parameters to be determined; $\alpha_{ak}$ is the exponential coefficient; and $n_{ak}$ corresponds to the power of the exponential function. The subscripts $a$ and $k$ denote the indices of atoms and basis functions, respectively.

We initialize `ExpBasisFuncHelper` using the default method, and therefore need to provide the $\alpha_{ak}$ (`exponents`), $n_{ak}$ (`exponents_orders`), and initial values of $c_{ak}$ (`initials`). To illustrate the functionality, we use three exponential functions with different $n$ values, i.e., 1 (Slater type), 1.5, and 2 (Gaussian type).

In [9]:
bs_dict = {
    "exponents_orders": {1: [1, 1.5, 2], 8: [1, 1.5, 2]},
    "exponents": {1: [0.1, 0.2, 0.3], 8: [1.0, 2.0, 3.0]},
    "initials": {1: [0.33] * 3, 8: [0.33] * 3},
}
basis_helper = ExpBasisFuncHelper(**bs_dict)

It should be noted that one can also initialize a `ExpBasisFuncHelper` through a `json` file by calling `ExpBasisFuncHelper.from_json('json_file_path.json')`.

Next, we can apply the newly customized basis functions and the self-consistent solver. It is important to note

In [10]:
def customized_basis_functions():
    kwargs = prepare_argument_dict(mol, grid, rho)
    kwargs["solver"] = customize_self_consistent_solver
    kwargs["basis_func"] = basis_helper
    part = LinearISAWPart(**kwargs)
    part.do_all()
    print_results(part)


customized_basis_functions()


Information of integral grids.
--------------------------------------------------------------------------------
Grid size of molecular grid: 18460
************************************ Atom 0 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
          18 18 18 18 18 18 26 26 26 26 38 38 38 38 38 50 50 50 50 50
          86 86 110 110 110 110 170 194 194 434 590 590 434 434 434 302 302 302 194 194
          170 110 110 110 110 110 110 110 110 110 110 110 86 50 50 18 18 18 18 18
          
************************************ Atom 1 ************************************
   |-- Radial grid size: 120
   |-- Angular grid sizes: 
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
          6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 18 18 18 18 18
   